ARCHS = armv7
include theos/makefiles/common.mk
BUNDLE_NAME = CTWiFiToggle
CTWiFiToggle_FILES = CTWiFiToggle.mm
CTWiFiToggle_INSTALL_PATH = /Library/Sideswitch/plugins
include $(THEOS_MAKE_PATH)/bundle.mk