ARCHS = armv7
include theos/makefiles/common.mk
BUNDLE_NAME = CTAirplaneMode
CTAirplaneMode_FILES = CTAirplaneMode.mm
CTAirplaneMode_INSTALL_PATH = /Library/Sideswitch/plugins
include $(THEOS_MAKE_PATH)/bundle.mk