ARCHS = armv7
include theos/makefiles/common.mk
BUNDLE_NAME = CTBluetoothToggle
CTBluetoothToggle_FILES = CTBluetoothToggle.mm
CTBluetoothToggle_INSTALL_PATH = /Library/Sideswitch/plugins
include $(THEOS_MAKE_PATH)/bundle.mk